<template lang="">
  <NuxtScrollbar tag="div">
    <div className="flex-1 overflow-y-auto">
        <MessageBox 
          :isOwn="true"
          key="message.id"
          data="message"
        />
        <MessageBox 
          :isOwn="false"
          key="message.id"
          data="message"
        />
        <MessageBox 
          :isOwn="true"
          key="message.id"
          data="message"
        />
        <MessageBox 
          :isOwn="false"
          key="message.id"
          data="message"
        />
        <MessageBox 
          :isOwn="true"
          key="message.id"
          data="message"
        />
        <MessageBox 
          :isOwn="false"
          key="message.id"
          data="message"
        />
        <MessageBox 
          :isOwn="true"
          key="message.id"
          data="message"
        />
        <MessageBox 
          :isOwn="false"
          key="message.id"
          data="message"
        />
        <MessageBox 
          :isOwn="true"
          key="message.id"
          data="message"
        />
        <MessageBox 
          :isOwn="false"
          key="message.id"
          data="message"
        />
        <MessageBox 
          :isOwn="true"
          key="message.id"
          data="message"
        />
        <MessageBox 
          :isOwn="false"
          key="message.id"
          data="message"
        />
        <MessageBox 
          :isOwn="true"
          key="message.id"
          data="message"
        />
      <div className="pt-24" />
    </div>
  </NuxtScrollbar>
</template>
<script setup lang="ts">
import MessageBox from './MessageBox.vue';
</script>
